### ISSUE TITLE
link don't work

### ISSUE THREAD

**Issue by choejaewon001** [MoSadie/ServerMainMenu-Lib#7]
![Screenshot 2024-11-20 053142](https://github.com/user-attachments/assets/cae9454f-d409-4032-9f14-73656f7ef21d)

this link don't work. in step 0

**Comment by MoSadie** [comment]
Looks like modrinth moved the page, I've updated the wiki to link to the correct page (https://support.modrinth.com/en/articles/8801191-modrinth-maven)

Thanks for letting me know!
